# Generated by Django 5.0.12 on 2025-02-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('date_of_data_collection', models.DateField()),
                ('age', models.IntegerField()),
                ('relationship', models.CharField(max_length=255)),
                ('guardian_occupation', models.CharField(max_length=255)),
                ('guardian_education', models.CharField(max_length=255)),
                ('respondent_religion', models.CharField(max_length=255)),
                ('family_size', models.IntegerField()),
                ('has_siblings', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('siblings_have_partners', models.CharField(blank=True, max_length=10, null=True)),
                ('gets_pocket_money', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('pocket_money_adequate', models.CharField(blank=True, max_length=10, null=True)),
                ('financial_support', models.CharField(max_length=255)),
                ('guardian_visits', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('alternative_visitor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocioEconomicDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socio_data', to='kemriinfluenza.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='SourcesInformationSexualBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_to_reproductive_health_info', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('information_adequate', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('educator_name', models.JSONField(default=list)),
                ('topic_name', models.JSONField(default=list)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_info', to='kemriinfluenza.questionnaire')),
            ],
        ),
    ]
