# Generated by Django 5.0.12 on 2025-02-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kemriinfluenza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesinformationsexualbehavior',
            name='educator_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcesinformationsexualbehavior',
            name='topic_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
