# Generated by Django 5.0.12 on 2025-02-20 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kemriinfluenza', '0002_alter_sourcesinformationsexualbehavior_educator_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='age',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='alternative_visitor',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='family_size',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='financial_support',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='gets_pocket_money',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='guardian_education',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='guardian_occupation',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='guardian_visits',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='has_siblings',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='pocket_money_adequate',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='respondent_religion',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='siblings_have_partners',
        ),
        migrations.RemoveField(
            model_name='socioeconomicdemographic',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='sourcesinformationsexualbehavior',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='alternative_visitor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='family_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='financial_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='gets_pocket_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='guardian_education',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='guardian_occupation',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='guardian_visits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='has_siblings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='pocket_money_adequate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='questionnaire_ref',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='socio_economic', to='kemriinfluenza.questionnaire'),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='relationship',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='respondent_religion',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='socioeconomicdemographic',
            name='siblings_have_partners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcesinformationsexualbehavior',
            name='questionnaire_ref',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='sexual_behavior', to='kemriinfluenza.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesinformationsexualbehavior',
            name='access_to_reproductive_health_info',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcesinformationsexualbehavior',
            name='educator_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcesinformationsexualbehavior',
            name='information_adequate',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcesinformationsexualbehavior',
            name='topic_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
