# Generated by Django 5.0.12 on 2025-02-20 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kemriinfluenza', '0003_remove_questionnaire_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomicdemographic',
            name='questionnaire_ref',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='socio_economic', to='kemriinfluenza.questionnaire'),
        ),
        migrations.AlterField(
            model_name='sourcesinformationsexualbehavior',
            name='questionnaire_ref',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='sexual_behavior', to='kemriinfluenza.questionnaire'),
        ),
    ]
