# Generated by Django 5.0.12 on 2025-02-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kemriinfluenza', '0004_alter_socioeconomicdemographic_questionnaire_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomicdemographic',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
